### DISCUSSION TITLE
Highlighting in "code" and spellchecking

### DISCUSSION THREAD

**Discussion by hue-ctrl** [TriliumNext/Trilium#1780] [Q&A]
Hello Community,

I have the odd requirement that I need to highlight text in code/shell-output that I copied from elsewhere into trilium. As real code-blocks do not allow highlighting, i managed to create an own `#cssClass` which emulates the code-blocks for all `<p>` when assigned to a note:
```css
.myMono p {
    display: block;
    unicode-bidi: embed;
    font-family: monospace;
    white-space: pre;
    background-color: rgba(199, 199, 199, 0.3);
    border-color: rgb(196, 196, 196);
    border-width: 1px;
    border-style: solid;
}
```
This works so far, but i can't find a way to disable spellchecking on a per-note basis, the `spellcheck`-attribute does not seem to be accessible via css. Has anybody tried something similar?
