### DISCUSSION TITLE
v0.48.0-beta release

### DISCUSSION THREAD

**Discussion by zadam** [TriliumNext/Trilium#2209] [General]
**This is a beta release and can contain serious bugs. Use for evaluation only.**

0.48 is a big release and contains many changes, the biggest are described on [release notes page](https://github.com/zadam/trilium/wiki/Release-notes-v0.48).

<hr /><em>This discussion was created from the release <a href='https://github.com/zadam/trilium/releases/tag/v0.48.0-beta'>v0.48.0-beta release</a>.</em>

**Comment by Nriver** [comment]
Wow, nice work. That's really a big UI change for Trilium.

**Comment by cnlzxin** [comment]
I'm sorry, but I have to say, the new page layout makes me feel a little uncomfortable. It's becoming the other, but not itself.

**Reply by abitofevrything** [reply]
I was the same at first, but after using the latest version (master branch) for about a month, I now think that the old UI is slightly more clunky and intrusive than the new one.

**Reply by cnlzxin** [reply]
I think a lot of time, but still stick to my point of view, the layout of old UI is more reasonable. For example, the location of note content and the display of link map, make me more comfortable to concentrate my attention, instead of dispersing to other places.

**Comment by sigaloid** [comment]
Absolutely loving the new redesign. Especially the built in calendar, makes it a whole lot more prominent; for some reason I had never noticed it.

**Reply by blumpcus** [reply]
Thank you for all the work you've put into the redesign/v.48.
I'm pretty ecstatic about split panes, workflow is immediately improved. 
Also, the fact that the split is tied to each tab so that I can have one tab with specific splits and another tab without them is very useful. 
Also, the themes are more polished and modern to my eyes, left-pane is clean. Dark-theme is much better.  
It's rare that I can say that I've only done minimal modifications to suit my own needs but that is the case here, kudos on the release.

**Comment by gerroon** [comment]
@zadam  do you have any plans for publicly shareable notes and folder in the upcoming versions? This is so needed in my view.

**Reply by sigaloid** [reply]
You can export a specific subtree as HTML and post it online; it even has a nice (static) tree structure on the left side, as well. This doesn't help for live editing or collaboration, but for publishing static notes, it works pretty well IMO, and I had no idea it existed. It is mentioned [here](https://github.com/zadam/trilium/wiki/Markdown) though. 

https://user-images.githubusercontent.com/69441971/136714219-02ae4f26-bdd7-42df-8961-b761936c38e7.mp4

**Reply by gerroon** [reply]
Sure that works in a super crude way, and the page looks like it is from the 90s. I guess it is better than nothing.

**Reply by sigaloid** [reply]
True :p 

Keep in mind it's being tracked here: https://github.com/zadam/trilium/discussions/2010 and here: https://github.com/zadam/trilium/issues/391

**Reply by zadam** [reply]
Info in #2010 is still valid.

**Reply by user9931** [reply]
export to markdown can be solution but unfortunately it does not export tables...

**Comment by JakeCoxon** [comment]
Looks good with dark sidebar and light content
![image](https://user-images.githubusercontent.com/601264/136986676-ea41f3ad-9a62-4c94-ab2f-11fed1d3bee1.png)

```css
:root {
    --left-pane-background-color: hsl(241, 7%, 18%);
    --launcher-pane-background-color: hsl(241, 7%, 18%);
    --left-pane-text-color: #bcbcbc;
    --launcher-pane-text-color: #bcbcbc;
    
    --active-item-background-color: #5c5c5c;
    --active-item-text-color: white;
    --main-border-color: transparent;
}

.fancytree-node {
    --main-background-color: transparent;
}

span.fancytree-node:hover {
    background: #363636;
}
```
