### DISCUSSION TITLE
How to force Trilium to create it's data folder on my Synology NAS?

### DISCUSSION THREAD

**Discussion by Unrepentant-Atheist** [TriliumNext/Trilium#2238] [Q&A]
Going with 
```
    ---
    version: '3.3'
    services:
        trilium:
            image: zadam/trilium
            container_name: trilium
            ports:
                - 4295:8080
            environment:
                - TRILIUM_DATA_DIR=/data
            volumes:
                - /volume1/docker/trilium:/data
            labels:
                - deunhealth.restart.on.unhealthy=true
            restart: always
    networks:
      default:
        name: dockernet
        external: true
```
I'm trying to force trilium to create its data folder on my synology-NAS folder
```
            environment:
                - TRILIUM_DATA_DIR=/data
            volumes:
                - /volume1/docker/trilium:/data
```
Problem is I get access permission denied errors: https://hastebin.com/ukegeguluy.typescript 

Pretty sure it's got do do with setting PUID and PGID like
```
    environment:
        - PUID=xxx
        - PGID=xxx
```
I'm just not sure which ones in trilium. Any ideas?
