### DISCUSSION TITLE
Better Documentation on how to upgrade to new version (server, docker-compose)

### DISCUSSION THREAD

**Discussion by TheNomad11** [TriliumNext/Trilium#2387] [General]
Trilium is the most impressive app I have encountered but documentation could be better, especially regarding upgrading for us who are no sysadmins and still learning. Currently the only available information for the recommended docker setup is:

>for docker server installation - pull the image of the newer version and restart

In the past, this did not work for me, I only got error message, therefore I was looking for a docker-compose file. After some searching I found a working one, now I did the standard `docker-compose stop`, `docker-compose pull`, `docker-compose up -d` but then it seemed my Trilium instance got wiped out, the first set-up screen appeared. It seems there have been upgrade issues before, see https://github.com/zadam/trilium/issues/1747, EDIT: also related to unresolved issue https://github.com/zadam/trilium/issues/1971

So what is the recommended way to update? 

And: Is using a docker-compose file recommended or not? 

My docker-compose file:

```
version: '2.1'
services:
  trilium:
    image: zadam/trilium:latest
    user: root
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/root/trilium-data
    ports:
      - "6080:8080"
    volumes:
      - /home/USER/trilium/trilium-data:/home/node/trilium-data
```

Thanks!

_(Will now try to restore from backup)_

**EDIT: Backup was not saved in data folder, I experimented with permissions and changed data folders, nothing worked, so some permission issues it seems**

**EDIT 1: This solution worked for me https://github.com/zadam/trilium/issues/1747#issuecomment-821555621
But the data directory is not as it shown in the backup section at /home/node but under root**
