### DISCUSSION TITLE
Unable to build and start image on Ubuntu Server 21.04 (arm64)

### DISCUSSION THREAD

**Discussion by drtech981** [TriliumNext/Trilium#2423] [Q&A]
Doing docker-compose up gives the following error : 
`COPY failed: file not found in build context or excluded by .dockerignore: stat server-package.json: file does not exist`

tried on a different system, same error comes up every time. What am I doing wrong ?

**Comment by zadam** [comment]
you need to run `bin/build-docker.sh`

**Comment by drtech981** [comment]
Thanks @zadam the build completed successfully but the container keeps exiting with the following error:
```
trilium    | node:internal/fs/utils:344
trilium    |     throw err;
trilium    |     ^
trilium    |
trilium    | Error: EACCES: permission denied, mkdir '/data/log'
trilium    |     at Object.mkdirSync (node:fs:1334:3)
trilium    |     at Object.<anonymous> (/usr/src/app/src/services/log.js:7:8)
trilium    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
trilium    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
trilium    |     at Module.load (node:internal/modules/cjs/loader:981:32)
trilium    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
trilium    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
trilium    |     at require (node:internal/modules/cjs/helpers:102:18)
trilium    |     at Object.<anonymous> (/usr/src/app/src/app.js:1:13)
trilium    |     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
trilium    |   errno: -13,
trilium    |   syscall: 'mkdir',
trilium    |   code: 'EACCES',
trilium    |   path: '/data/log'
trilium    | }
```

**Reply by zadam** [reply]
How do you run it? Is /data/ mounted somewhere on the host?

**Reply by drtech981** [reply]
```
version: '2.1'
services:
  trilium:
    container_name: trilium
    image: zadam/trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "8009:8080"
    volumes:
      - /docker/trilium:/data
```
This is the modified docker-compose file I'm using.
The directory /docker/trilium has chmod of 777
