### DISCUSSION TITLE
Theme not working since update

### DISCUSSION THREAD

**Discussion by Sebiann** [TriliumNext/Trilium#2433] [Q&A]
![image](https://user-images.githubusercontent.com/32842507/145673530-bd5cf5c8-bd9c-4e3f-97c5-c105bab5467e.png)
```css
:before {
content: '';
z-index: -100;
position: absolute;
left: 0;
right: 0;
top: 0;
bottom: 0;
-webkit-filter: blur(3px);
background: linear-gradient(rgba(0,0,0,.8), rgba(0,0,0,.95)), url('/custom/image/miku-hatsune.jpg') no-repeat;
background-size: cover;
}
```
So ever since an update i had to change my themes code for it too work. Used to be `body.theme-miku-hatsune:before` now its just `:before`

Problem is now it gives like this echo effect, were it tries to apply the `:before` in every part of the ui it can find.

**Comment by XXXJetfireXXX** [comment]
Looks like I figured this out:
![image](https://user-images.githubusercontent.com/43646178/157170242-bb74244a-249a-4380-aa19-645d0edb8c17.png)

You just need to use `body` instead and voila!

**Reply by Sebiann** [reply]
Could you once look at my code. its still having some problems on the sidebar. Im also gonna recheck it this evening since im in school right now.

```css
/*
Stole the demo
 */


/*
Mirror:
transform: scale(-1, 1);
*/

@font-face { /* This will be used as main UI font (see below) */
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  src: url('/custom/fonts/raleway.woff2') format('woff2');
}

@font-face { /* This will be used as text content font (see below) */
  font-family: 'Garamond';
  font-style: normal;
  font-weight: 400;
  src: url('/custom/fonts/garamond.woff2') format('woff2');
}

body {
content: '';
z-index: -100;
position: absolute;
left: 0;
right: 0;
top: 0;
bottom: 0;
/* -webkit-filter: blur(3px);  */
background: linear-gradient(rgba(0,0,0,.8), rgba(0,0,0,.95)), url('/custom/image/miku-hatsune.jpg') no-repeat;
background-size: cover;
}

:root {
    --main-font-family: 'Raleway' !important;
    --main-font-size: normal;
    --tree-font-family: inherit;
    --tree-font-size: normal;
    --detail-font-family: inherit;
    --detail-font-size: normal;
    --detail-text-font-family: 'Garamond' !important;

    --main-background-color: #404552;
    --main-text-color: #AFB8C6;
    --main-border-color: #AFB8C6;
    --accented-background-color: #383C4A;
    --more-accented-background-color: #2F343F;
    --header-background-color: #383C4A;
    --button-background-color: #2F343F;
    --button-disabled-background-color: #404552;
    --button-border-color: #333;
    --button-text-color: #AFB8C6;
    --button-border-radius: 2px;
    --primary-button-background-color: #6c757d;
    --primary-button-text-color: white;
    --primary-button-border-color: #6c757d;
    --muted-text-color: #86919F;
    --input-text-color: #AFB8C6;
    --input-background-color: #404552;
    --hover-item-text-color: white;
    --hover-item-background-color: #4877B1;

    --menu-text-color: #AFB8C6;
    --menu-background-color: #383C4A;
    --tooltip-background-color: #383C4A;
    --link-color: lightskyblue;
    --modal-background-color: #404552;
    --modal-backdrop-color: black;
    --scrollbar-border-color: rgba(175, 184, 198, 0.5);
}


body.theme-miku-hatsune .note-detail-text {
    font-size: 120%; /* Garamond is subjectively smaller */
}

body.theme-miku-hatsune .CodeMirror {
    filter: invert(100%) hue-rotate(180deg);
}
```
