### DISCUSSION TITLE
Does Trilium Docker installation support volume for persistant data?

### DISCUSSION THREAD

**Discussion by HubKing** [TriliumNext/Trilium#2856] [Q&A]
[The YML file in the root directory ](https://github.com/zadam/trilium/blob/master/docker-compose.yml)seemed old, so, I created my own like the one below, but it fails because it cannot access the data directory. I have tried the YML file in the root directory and it had the same problem. In the [documentation file](https://github.com/zadam/trilium/wiki/Docker-server-installation), it seems be explaining how to use Trilium with what Docker calls "bind mount". 

Is "volume" not supported? Is that a bug or is there any reason why volume cannot be used and only bind mount should be used? I do not know Docker well, but I read that the process in the container can get the root privilege. Can't this permission problem be fixed by changing the permission of TRILIUM_DATA_DIR inside of the container?

I navigated into /var/lib/docker/volumes... and modified the permission of the `_data` directory to 777 and then Trilum started. But this is probably not a recommended method, I think, because the volume is supposed to be managed by Docker.

````
version: "3.7"

name: trilium

volumes:
  data:
    driver: local

services:
  server:
    build:
      context: .
    image: zadam/trilium
    environment:
      - TRILIUM_DATA_DIR=/data
    restart: always
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
      - "8022:22"
````
Output
````
 ⠿ Volume "trilium_data"       Created                                                                                                                                        0.0s
 ⠿ Container trilium-server-1  Created                                                                                                                                        0.0s
Attaching to trilium-server-1
trilium-server-1  | node:internal/fs/utils:344
trilium-server-1  |     throw err;
trilium-server-1  |     ^
trilium-server-1  |
trilium-server-1  | Error: EACCES: permission denied, mkdir '/data/log'
trilium-server-1  |     at Object.mkdirSync (node:fs:1336:3)
trilium-server-1  |     at Object.<anonymous> (/usr/src/app/src/services/log.js:8:8)
trilium-server-1  |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
trilium-server-1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
trilium-server-1  |     at Module.load (node:internal/modules/cjs/loader:981:32)
trilium-server-1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
trilium-server-1  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
trilium-server-1  |     at require (node:internal/modules/cjs/helpers:102:18)
trilium-server-1  |     at Object.<anonymous> (/usr/src/app/src/app.js:1:13)
trilium-server-1  |     at Module._compile (node:internal/modules/cjs/loader:1103:14) {
trilium-server-1  |   errno: -13,
trilium-server-1  |   syscall: 'mkdir',
trilium-server-1  |   code: 'EACCES',
trilium-server-1  |   path: '/data/log'
trilium-server-1  | }
trilium-server-1 exited with code 1

````
