### DISCUSSION TITLE
How to color tree icons.

### DISCUSSION THREAD

**Discussion by Korozion** [TriliumNext/Trilium#2871] [Q&A] [answered]
Hi there,
A few versions ago, I was able to add some custom colors in the tree hierarchy by defining colors in theme file :
`body.theme-custom1 .fancytree-node.orange .fancytree-custom-icon { color: orange; }`
and by adding the attribute `#cssClass=orange` to the folder I wanted to color.

This does not work anymore. Can somebody help me making it work ?

**Comment by zadam** [comment, marked as answer]
Hi, just remove the `body.theme-custom1` and it will work again.

```css
.fancytree-node.orange .fancytree-custom-icon { color: orange; }
```
