### DISCUSSION TITLE
How to style a particular Text Note with CSS

### DISCUSSION THREAD

**Discussion by ferrlen** [TriliumNext/Trilium#2948] [Q&A] [answered]
How to add CSS to customize a particular Text Note?

**Comment by ferrlen** [comment, marked as answer]
To customize the CSS of only a few notes, you can create a `Note type: CSS` and add to it a `#appCss` label with the name of your custom CSS (for example: `#appCss=myCustomCss`). Then, add the label `cssClass` to the notes you want to customize (e.g.: `#cssClass=myCustomCss`). 

Additional remarks:
- I think one must add `!important` for the CSS rule to have enough specificity.
- You need to reload the frontend for changes to be applied. You click on Menu > Reload frontend or press `Ctrl + R` for that.
- To apply the CSS style to all children notes, add `(inheritable)` to parent's `#cssClass`, like so: `#cssClass(inheritable)=myCustomCss` .

### Example:
- Create a `Note type: CSS` and add this `owned attribute` to it: `#appCss=testing`
- Create a regular `Text Note` and add `owned attribute` label: `#cssClass=testing`
- Add 2 CSS rules for testing:
```css
/*** 
class `.note-detail` here will make the first rule only apply to the writing part of the Text Note, 
otherwise <p> elements elsewhere in the note, like the Owned Attributes section, will also inherit this rule. 

I'm leaving this out in the second rule so you can see that the Owned Attributes section will now have a yellow background-color
***/

.testing .note-detail p {
  color: red !important;
}

.testing p {
  background-color: yellow !important;
}
```

### Explanation:

A *CSS Note* with `#appCss` is [applied  globally](https://github.com/zadam/trilium/discussions/1568).

Labeling a *Text Note* with `#cssClass=testing` will add `testing` to the CSS classlist of this note. Thus, the `.testing` CSS selector will match it.

Because the first CSS rule (`color: red`) had also the `.note-detail` selector, it behaves as expected. However, the second rule (`background-color: yellow`) does not make this restriction and, as such, is applied everywhere in the note, including in unexpected places like the Owned Attributes section in the top bar.

* * * 

Remaining questions:

How does `#cssClass` work exactly? Where is it added?
