### DISCUSSION TITLE
Hide attributes in child view

### DISCUSSION THREAD

**Discussion by xsmyqf** [TriliumNext/Trilium#3254] [Ideas] [answered]
Can we hide the attributes in the father note view acquiescently?
![image](https://user-images.githubusercontent.com/6007829/198519547-6e8066f4-a75f-40d5-ae74-399289e35f4a.png)

**Comment by zadam** [comment, marked as answer]
Hi, you could hide it with a [custom CSS](https://github.com/zadam/trilium/wiki/Themes#custom-css):

```css
.rendered-note-attributes {
    display: none;
}
```
