### DISCUSSION TITLE
Docker Compose + Nginx reverse proxy: error 502 Bad Gateway, Connection reset by peer

### DISCUSSION THREAD

**Discussion by Andrewskiz** [TriliumNext/Trilium#3559] [General]
Hey, I just installed Trilium via Docker Compose and I am having trouble with nginx and a reverse proxy. 

Here is my docker-compose.yml (I changed the port since I have another service running on port 8080)

```
version: '2.1'
services:
  trilium:
    image: zadam/trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - "127.0.0.1:8050:8050"
    volumes:
      - trilium:/home/node/trilium-data

volumes:
  trilium:

```

and the reverse proxy section in my nginx config:

```
location /trilium/ {
    proxy_pass http://127.0.0.1:8050/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}
```

There are no errors in the docker container logs, and this is the status on docker:

```
CONTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS                  PORTS                                NAMES
************   zadam/trilium                 "docker-entrypoint.s…"   23 hours ago   Up 23 hours (healthy)   127.0.0.1:8050->8050/tcp, 8080/tcp   triliumdocker_trilium_1
```

When I try to visit https://mydomain.com/trilium/ I get error 502 Bad Gateway. This is the error I am getting in my nginx log:

`2023/01/24 17:12:01 [error] 1110637#1110637: *1565 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: my ip, server: mydomain.com, request: "GET /trilium/ HTTP/1.1", upstream: "http://127.0.0.1:8050/", host: "mydomain.com"`

I'm still new to docker and reverse proxies, so I've probably made a error somewhere. Any help would be greatly appreciated,  thank you!

**Comment by LukeSkywalker993** [comment]
same here since last Update of nginx

i using teslamate and ip-symcon.

**Comment by Nriver** [comment]
Check the output of `curl http://127.0.0.1:8050/`.

**Comment by Andrewskiz** [comment]
curl: (56) Recv failure: Connection reset by peer

**Reply by Nriver** [reply]
I suppose you did not change the running port of Trilium in the ini config file, and make the port mapping to an empty port. Try to modify the `ports` part of the compose file to `- "8050:8080"` and restart your docker conatiner.

**Reply by Andrewskiz** [reply]
> I suppose you did not change the running port of Trilium in the ini config file, and make the port mapping to an empty port. Try to modify the `ports` part of the compose file to `- "8050:8080"` and restart your docker conatiner.

I changed the ports section set to `- "8050:8080"` I also tried it without the -d argument and got this output:


```

trilium_1  | No USER_UID specified, leaving 1000
trilium_1  | No USER_GID specified, leaving 1000
trilium_1  | DB not initialized, please visit setup page - http://[your-server-host]:8080 to see instructions on how to initialize Trilium.
trilium_1  | DB size: 4 KB
trilium_1  | Trusted reverse proxy: false
trilium_1  | App HTTP server starting up at port 8080

```
I am not sure if it is still trying to run on port 8080 despite specifying 8050 in the docker-compose.yml file

Docker ps shows this:

CONTAINER ID   IMAGE                         COMMAND                  CREATED         STATUS                    PORTS                                                 NAMES
************   zadam/trilium                 "docker-entrypoint.s…"   4 minutes ago   Up 46 seconds (healthy)   0.0.0.0:8050->8050/tcp, :::8050->8050/tcp, 8080/tcp   triliumdocker_trilium_1

And I'm still get the 502 Bad Gateway from nginx / Recv failure: Connection reset by peer from curl

**Comment by return215** [comment]
My setup is similar, but I use `nginx-proxy` and `acme-companion` containers to also setup HTTPS for my site and my notes.

Here is my `docker-compose config output`:

```yml
services:
  server:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:1.1
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    restart: always
    volumes:
    - certs:/etc/nginx/certs:rw
    - vhost:/etc/nginx/vhost.d:rw
    - www:/usr/share/nginx/html:rw
    - /var/run/docker.sock:/tmp/docker.sock:ro
  site:
    container_name: site
    depends_on:
    - ssl
    environment:
      LETSENCRYPT_EMAIL: mail@mydomain.xyz
      LETSENCRYPT_HOST: mydomain.xyz
      VIRTUAL_HOST: mydomain.xyz
    image: nginx:stable
    restart: always
  ssl:
    container_name: acme-companion
    depends_on:
    - server
    environment:
      DEFAULT_EMAIL: mail@mydomain.xyz
      NGINX_PROXY_CONTAINER: nginx-proxy
    image: nginxproxy/acme-companion:2.2
    restart: always
    volumes:
    - certs:/etc/nginx/certs:rw
    - vhost:/etc/nginx/vhost.d:rw
    - www:/usr/share/nginx/html:rw
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - acme:/etc/acme.sh:rw
  trilium:
    container_name: trilium
    depends_on:
    - ssl
    environment:
      LETSENCRYPT_EMAIL: mail@mydomain.xyz
      LETSENCRYPT_HOST: notes.mydomain.xyz
      VIRTUAL_HOST: notes.mydomain.xyz
      VIRTUAL_PORT: 8080
    image: zadam/trilium:0.58-latest
    ports:
    - published: 8080
      target: 8080
    restart: always
    volumes:
    - certs:/home/node/certs:rw
    - acme:/home/node/acme:rw
    - /var/local/trilium-data:/home/node/trilium-data:rw
version: '3.3'
volumes:
  acme: {}
  certs: {}
  vhost: {}
  www: {}
```

The logs from `nginx-proxy` returns this when I access my site and my notes subdomain.
```
nginx-proxy | nginx.1     | mydomain.xyz ***.***.***.*** - - [10/Feb/2023:02:19:23 +0000] "GET / HTTP/2.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0" "***.***.***.***:80"
nginx-proxy | nginx.1     | 2023/02/10 02:19:24 [error] 77#77: *33 upstream prematurely closed connection while reading response header from upstream, client: ***.***.***.***, server: notes.mydomain.xyz, request: "GET / HTTP/2.0", upstream: "http://***.***.***.***:8080/", host: "notes.mydomain.xyz"
nginx-proxy | nginx.1     | notes.mydomain.xyz ***.***.***.*** - - [10/Feb/2023:02:19:24 +0000] "GET / HTTP/2.0" 502 157 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0" "***.***.***.***:8080"
```

All other containers run without any errors. However, I noticed something in `docker-compose ps` (also in `docker ps` but basically the same as this):
```
acme-companion   /bin/bash /app/entrypoint. ...   Up                                                                                     
nginx-proxy      /app/docker-entrypoint.sh  ...   Up               0.0.0.0:443->443/tcp,:::443->443/tcp, 0.0.0.0:80->80/tcp,:::80->80/tcp
site             /docker-entrypoint.sh ngin ...   Up               80/tcp                                                                
trilium          docker-entrypoint.sh ./sta ...   Up (unhealthy)   0.0.0.0:8080->8080/tcp,:::8080->8080/tcp  
```

`trilium` container is in "unhealthy" status but running. Is there any errors in my setup and how should I go about fixing it?
