### DISCUSSION TITLE
Change Location of Backlink Button

### DISCUSSION THREAD

**Discussion by somecrepe** [TriliumNext/Trilium#3622] [Q&A] [answered]
The backlink button appears in the text body and can cover words, is there anyway to move it to a side bar? Or stop it from appearing when opening a note?
I'm using app version 0.58.8

**Comment by zadam** [comment]
It's possible to temporarily hide it with the close button. Otherwise no.

**Comment by XXXJetfireXXX** [comment, marked as answer]
You can make it less intrusive by fiddling with these parameters:
![image](https://user-images.githubusercontent.com/43646178/219872861-f45aea9e-4aac-4daa-924f-452404bd82e2.png)
![image](https://user-images.githubusercontent.com/43646178/219873112-3f1309bc-d71f-4d2c-b2a9-bb5aba73da16.png)

For example, by adding this to a [custom theme](https://github.com/zadam/trilium/wiki/Themes):
```css
.backlinks-ticker{
  opacity: 20%!important;
}
.backlinks-count{
  font-size: 7px;
}
```
you can make it look like this:
![image](https://user-images.githubusercontent.com/43646178/219873186-8c011112-9df6-4a59-a216-14467b0b2038.png)

To hide it completely, just add this instead:
```css
.backlinks-ticker{
  display: none!important;
}
```
![image](https://user-images.githubusercontent.com/43646178/219874034-c0a8c917-4869-4477-97f0-a7927f0216a4.png)

**Reply by XXXJetfireXXX** [reply]
As of moving it somewhere else... well, it's a bit clunky but it works as a quick solution.
It's far from perfect since you'd probably have to manually adjust some stuff but you get the idea.
![image](https://user-images.githubusercontent.com/43646178/219877910-051e7c11-ccb7-4b2b-89f9-981efd41117c.png)

Backlinks items window:
![image](https://user-images.githubusercontent.com/43646178/219876446-7ce60ef6-532a-47f3-b35b-fe6cd16f76f6.png)

```css
.floating-buttons{
  position: absolute!important;
  /*These control the position of the buttons*/
  left: 3px;
  bottom: 300px;
}
.floating-buttons-children{
  position: relative!important;
  right: 0px;
  top: 0px;
  display: inline-table!important;
  flex-direction: column!important;
}
.floating-buttons-children > button, .floating-buttons-children .floating-button{
  padding: 5px 10px 28px 10px!important;
}
.backlinks-count{
  font-size: 10px;
}
.backlinks-items{
  position: fixed!important;
}
```
