### DISCUSSION TITLE
Improve visibility of active calendar days (days that have a corresponding note in journal)

### DISCUSSION THREAD

**Discussion by XXXJetfireXXX** [TriliumNext/Trilium#4100] [Show and tell]
This small tweak aims to improve visibility for 'active' calendar days since underlining them is definitely not enough for me.

![image](https://github.com/zadam/trilium/assets/43646178/8d164f93-bea8-4a7d-9690-2c02a9b48d03)

To apply the tweak, place this in your custom css theme:
```css
.calendar-dropdown-widget .calendar-date-exists{
    color: deepskyblue;
}
```
You can further customize it to your liking by changing color or adding more rules.
