### DISCUSSION TITLE
Hiding shared note info banner/widget

### DISCUSSION THREAD

**Discussion by ohmstance** [TriliumNext/Trilium#4146] [Q&A] [answered]
I am sharing one of my note to public. However, I'd like to hide the info widget that tells me I'm sharing the note as it is taking vertical screen space. Is there a way to hide this banner/widget? See the following image for illustration:

![image](https://github.com/zadam/trilium/assets/58171737/d1b9533c-0d3c-4f4d-98e8-051436877dd0)

**Comment by zadam** [comment, marked as answer]
There isn't such possibility in the app. If you know CSS, you can hide it with [custom styles](https://github.com/zadam/trilium/wiki/Themes#custom-css), though.

**Comment by ohmstance** [comment]
I see. I've went ahead with hiding it in CSS in my personal theme. I've made it so the widget remains for 3 seconds upon note load, then hides. When hovered on, it stops animating for a chance to copy the URL.

https://github.com/zadam/trilium/assets/58171737/6fdeaeeb-509d-4253-be6c-41bd0b94570a

I used the following CSS:
```css
/* Hide shared note info widget after page load so it doesn't take vertical space */
@keyframes retract {
    to {
        opacity: 0; max-height: 0; border: none;
        margin-top: 0; margin-bottom: 0; 
        padding-top: 0; padding-bottom: 0;
    }
}
#root-widget .shared-info-widget {
    max-height: 100%;
    animation: retract 0.5s forwards 3s;
}
#root-widget .shared-info-widget:hover {
    animation: unset;
}
```
Thank you for making Trilium.
