### DISCUSSION TITLE
ERROR: Current DB version 228 is newer than the current DB version 227

### DISCUSSION THREAD

**Discussion by thehijacker** [TriliumNext/Trilium#4596] [Q&A] [answered]
My docker instance of Trilium would not start anymore. Looking at logs I can see:

`ERROR: Current DB version 228 is newer than the current DB version 227, which means that it was created by a newer and incompatible version of Trilium. Upgrade to the latest version of Trilium to resolve this issue.`

But I am using latest docker image in docker-compose:

```
  trilium:
    image: zadam/trilium
    container_name: trilium
    environment:
      - TZ=Europe/Ljubljana
    ports:
      - 18080:8080
    volumes:
      - /mnt/usb_1/Docker/Trilium/data:/home/node/trilium-data
    restart: unless-stopped
```

Any idea how I can fix this? Thank you.
