### DISCUSSION TITLE
Custom Table of Contents (TOC) Headers

### DISCUSSION THREAD

**Discussion by BiigBeaker** [TriliumNext/Trilium#5866] [General]
I'm not much of a coder so forgive me if this is stupid but lately I've been creating a lot of documentation and I wanted to color code the headers and associated table of contents. I have no issue color coding the headers inside of the note using a .css but these changes don't seem to reflect the associated sections inside of the table of contents.

I've attempted making a separate .css for the table of contents but I'm not getting anywhere. I've made many iterations to the code but I just can't get it to work correctly. I'll have the current code listed below called 'custom-toc' 

### **Problem:**
I am able to change header formatting with custom css in the notes itself but these changes do not also apply to the table of contents. The current custom css that I am using is shown below.

### **custom-header.css**
`/* Header styles for note content */
.custom-headers h2 {
  color: #4ce699 !important;
  font-weight: bold;
}
.custom-headers h3 {
  color: #e6994c !important;
  font-weight: bold;
}
.custom-headers h4 {
  color: #4c99e6 !important;
  font-weight: bold;
}
.custom-headers h5 {
  color: #e64c4c !important;
  font-weight: bold;
}`

The parent folder that contains the notes that I am attempting to modify has the following attribute:  #cssClass(inheritable)=custom-headers 

### **custom-toc.css**
`/* TOC styles for corresponding header levels */
.toc-widget .toc > ol > li > span {
  color: #4ce699 !important;
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > span {
  color: #e6994c !important;
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > ol > li > span {
  color: #4c99e6 !important;
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > ol > li > ol > li > span {
  color: #e64c4c !important;
  font-weight: bold;
}`

As for the attribute section for the parent folder, I've attempted multiple different values for attribute labels with the name of cssClass. Values I have tried are toc-widget, toc, and even toc-widget-toc. Nothing seems to work

### **My Goal:**
I want to change header colors based on header type. For example, all h2 headers should be green, h3 headers orange, h4 headers blue. The document also contains a table of content (toc). Lets say the h2 named "Required Role Permissions" is orange, I would like the associated header in the toc also named "Required Role Permissions" to share them same color.

**Comment by dosubot** [comment]
Your CSS selectors for the TOC are correct for targeting header levels by their nesting depth, since TriliumNext's TOC uses a nested list structure without header-level classes. If your styles aren't showing up, it's likely due to CSS specificity or conflicts with the default theme. 

Try increasing selector specificity, for example:

```css
.toc-widget .toc > ol > li > span {
  color: #4ce699 !important;
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > span {
  color: #e6994c !important;
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > ol > li > span {
  color: #4c99e6 !important;
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > ol > li > ol > li > span {
  color: #e64c4c !important;
  font-weight: bold;
}
```

If that still doesn't work, inspect the TOC in your browser's developer tools to check for unexpected classes or style overrides. You may also want to use the `#shareOmitDefaultCSS` tag to prevent default styles from interfering with your custom CSS, as CSS conflicts between custom and default themes are a known issue in TriliumNext Notes ([discussion](https://github.com/orgs/TriliumNext/discussions/2358)).

There is currently no way to automatically match header colors between the note and the TOC by class or text—matching by nesting depth is the only option unless the code is changed to add more semantic classes. If Trilium's structure changes in the future, you may need to update your selectors accordingly. 

Let me know if you need help with inspecting the TOC or further troubleshooting!



*To reply, just mention [@dosu](https://go.dosu.dev/dosubot).*

---
<sup>How did I do? [Good](https://app.dosu.dev/response-feedback/bcf15e92-bbf7-4489-91f3-e2c659186f1a?feedback_type=great_response) | [Irrelevant](https://app.dosu.dev/response-feedback/bcf15e92-bbf7-4489-91f3-e2c659186f1a?feedback_type=irrelevant_answer) | [Incorrect](https://app.dosu.dev/response-feedback/bcf15e92-bbf7-4489-91f3-e2c659186f1a?feedback_type=incorrect_sources) | [Verbose](https://app.dosu.dev/response-feedback/bcf15e92-bbf7-4489-91f3-e2c659186f1a?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/bcf15e92-bbf7-4489-91f3-e2c659186f1a?feedback_type=hallucination) | [Report 🐛](https://app.dosu.dev/response-feedback/bcf15e92-bbf7-4489-91f3-e2c659186f1a?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/bcf15e92-bbf7-4489-91f3-e2c659186f1a?feedback_type=other)</sup>&nbsp;&nbsp;[![Join Discord](https://img.shields.io/badge/join-5865F2?logo=discord&logoColor=white&label=)](https://go.dosu.dev/discord-bot)&nbsp;[![Share on X](https://img.shields.io/badge/X-share-black)](https://twitter.com/intent/tweet?text=%40dosu_ai%20helped%20me%20solve%20this%20issue!&url=https%3A//github.com/TriliumNext/Notes/issues/2360)

**Comment by dosubot** [comment]
The reason your custom TOC CSS isn't working is because the TriliumNext Notes table of contents doesn't use <span> tags for the header text. Instead, each TOC entry is a <li> containing a <div class="item-content"> for the visible text, and the TOC is built from nested <ol> lists to represent header levels. There are no special classes for header depth, so you need to use CSS selectors that target the nesting level of the lists.

Here's how you can color-code the TOC entries by header level (h2, h3, h4, h5):

```css
/* TOC styles for corresponding header levels */
.toc-widget .toc > ol > li > .item-content {
  color: #4ce699 !important; /* h2 */
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > .item-content {
  color: #e6994c !important; /* h3 */
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > ol > li > .item-content {
  color: #4c99e6 !important; /* h4 */
  font-weight: bold;
}
.toc-widget .toc > ol > li > ol > li > ol > li > ol > li > .item-content {
  color: #e64c4c !important; /* h5 */
  font-weight: bold;
}
```

Make sure your custom CSS is loaded by TriliumNext Notes (for example, by using the `#cssClass` attribute or the global custom CSS feature). You do not need to set the cssClass to "toc-widget" or similar; just ensure your CSS targets the correct selectors as above.

This approach matches the TOC structure as implemented in TriliumNext Notes, where each header level is represented by deeper nesting of `<ol>` and `<li>` elements, and the header text is always inside a `.item-content` div. You can adjust the colors as needed to match your header styles.  
[Reference: TOC structure and classes](https://github.com/TriliumNext/Notes/blob/cca8504796ef25b2e24f3b55bd620c647b6d71c0/apps/client/src/widgets/toc.ts)



*To reply, just mention [@dosu](https://go.dosu.dev/dosubot).*

---
<sup>How did I do? [Good](https://app.dosu.dev/response-feedback/04744c4d-1fc7-4085-84c6-e8343f585905?feedback_type=great_response) | [Irrelevant](https://app.dosu.dev/response-feedback/04744c4d-1fc7-4085-84c6-e8343f585905?feedback_type=irrelevant_answer) | [Incorrect](https://app.dosu.dev/response-feedback/04744c4d-1fc7-4085-84c6-e8343f585905?feedback_type=incorrect_sources) | [Verbose](https://app.dosu.dev/response-feedback/04744c4d-1fc7-4085-84c6-e8343f585905?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/04744c4d-1fc7-4085-84c6-e8343f585905?feedback_type=hallucination) | [Report 🐛](https://app.dosu.dev/response-feedback/04744c4d-1fc7-4085-84c6-e8343f585905?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/04744c4d-1fc7-4085-84c6-e8343f585905?feedback_type=other)</sup>&nbsp;&nbsp;[![Join Discord](https://img.shields.io/badge/join-5865F2?logo=discord&logoColor=white&label=)](https://go.dosu.dev/discord-bot)&nbsp;[![Share on X](https://img.shields.io/badge/X-share-black)](https://twitter.com/intent/tweet?text=%40dosu_ai%20helped%20me%20solve%20this%20issue!&url=https%3A//github.com/orgs/TriliumNext/discussions/2361)
