### DISCUSSION TITLE
Trouble setting up TriliumNext

### DISCUSSION THREAD

**Discussion by avinatempest** [TriliumNext/Trilium#5874] [Ideas] [answered]
### Description
I'm trying to deploy TriliumNext (0.94.1) on a Raspberry Pi 5 running Ubuntu Server 24.04 through Portainer Stacks. I followed the Docker Compose installation instructions and modified the docker compose file a bit to include my preferred data directory. Unfortunately I am getting a looping error whenever I start the container. 

### The Error/Logs 

```
  path: '/home/avinatempest/Docker/TriliumNext/data'
}
Node.js v22.16.0
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000

node:fs:1364
  const result = binding.mkdir(
                         ^
Error: ENOENT: no such file or directory, mkdir '/home/avinatempest/Docker/TriliumNext/data'
    at Object.mkdirSync (node:fs:1364:26)
    at V0e (/usr/src/app/main.cjs:1:43307)
    at Iwn (/usr/src/app/main.cjs:1:42202)
    at /usr/src/app/main.cjs:1:43473
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:6:5026
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:712:2768
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:712:3417 {

  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/home/avinatempest/Docker/TriliumNext/data'
}
Node.js v22.16.0
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000

node:fs:1364
  const result = binding.mkdir(
                         ^
Error: ENOENT: no such file or directory, mkdir '/home/avinatempest/Docker/TriliumNext/data'
    at Object.mkdirSync (node:fs:1364:26)
    at V0e (/usr/src/app/main.cjs:1:43307)
    at Iwn (/usr/src/app/main.cjs:1:42202)
    at /usr/src/app/main.cjs:1:43473
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:6:5026
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:712:2768
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:712:3417 {

  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/home/avinatempest/Docker/TriliumNext/data'
}
Node.js v22.16.0
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000

node:fs:1364
  const result = binding.mkdir(
                         ^
Error: ENOENT: no such file or directory, mkdir '/home/avinatempest/Docker/TriliumNext/data'
    at Object.mkdirSync (node:fs:1364:26)
    at V0e (/usr/src/app/main.cjs:1:43307)
    at Iwn (/usr/src/app/main.cjs:1:42202)
    at /usr/src/app/main.cjs:1:43473
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:6:5026
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:712:2768
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:712:3417 {

  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/home/avinatempest/Docker/TriliumNext/data'
}
Node.js v22.16.0
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000

node:fs:1364
  const result = binding.mkdir(
                         ^
Error: ENOENT: no such file or directory, mkdir '/home/avinatempest/Docker/TriliumNext/data'
    at Object.mkdirSync (node:fs:1364:26)
    at V0e (/usr/src/app/main.cjs:1:43307)
    at Iwn (/usr/src/app/main.cjs:1:42202)
    at /usr/src/app/main.cjs:1:43473
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:6:5026
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:712:2768
    at /usr/src/app/main.cjs:1:231
    at /usr/src/app/main.cjs:712:3417 {

  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/home/avinatempest/Docker/TriliumNext/data'
}
Node.js v22.16.0

```

### Docker Compose File 

```
# Running `docker-compose up` will create/use the "trilium-data" directory in the user home
# Run `TRILIUM_DATA_DIR=/path/of/your/choice docker-compose up` to set a different directory
# To run in the background, use `docker-compose up -d`
services:
  trilium:
    # Optionally, replace `latest` with a version tag like `v0.90.3`
    # Using `latest` may cause unintended updates to the container
    image: triliumnext/notes:latest
    # Restart the container unless it was stopped by the user
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/avinatempest/Docker/TriliumNext/data
    ports:
      # By default, Trilium will be available at http://localhost:8080
      # It will also be accessible at http://<host-ip>:8080
      # You might want to limit this with something like Docker Networks, reverse proxies, or firewall rules,
      # however be aware that using UFW is known to not work with default Docker installations, see:
      # https://docs.docker.com/engine/network/packet-filtering-firewalls/#docker-and-ufw
      - '5000:8080'
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      # This can also be changed with by replacing the line below with `- /path/of/your/choice:/home/node/trilium-data
      - /home/avinatempest/Docker/TriliumNext/data:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```
 
The logs mention - `No USER_UID specified, leaving 1000` and `No USER_GID specified, leaving 1000`. My actual UID and GID are 1000 and 1003, was I supposed to somehow mention them? Because I did not see environment variables listed for them in the documentation, nor are they there in the default `docker-compose.yml` file... 
 
P.S - I tried deploying it again without using Portainer, I am unfortunately getting the same error. Prior to starting this discussion I did a search and came across a similar issue - https://github.com/orgs/TriliumNext/discussions/1166, I wasn't able to get the solution marked in that thread to work. I'm a novice to all this and any help is appreciated, thank you.
