### DISCUSSION TITLE
How to add custom fonts to TriliumNext Docker Server

### DISCUSSION THREAD

**Discussion by UnixTheWanderer** [TriliumNext/Trilium#5902] [Ideas] [answered]
So I want to simply(or I hope simply) add the opendyslexic font and was wondering how to do this?

**Comment by SiriusXT** [comment, marked as answer]
Here’s a method for reference:  
**Step 1**: Add `opendyslexic.woff2` as a file note in Trilium (you can drag it directly into the tree on the left sidebar), then add the following attributes:  
`#originalFileName=opendyslexic.woff2 #customResourceProvider="fonts/opendyslexic.woff2"`  

**Step 2**: Create a CSS note, add the following code, and include the attribute `#appCss`:  
```css
body {
   --detail-font-family: 'opendyslexic', sans-serif !important;
   --tree-font-family: 'opendyslexic', sans-serif !important;
   --bs-body-font-family: 'opendyslexic', sans-serif !important;
   --main-font-family: 'opendyslexic', sans-serif !important;
   /* --monospace-font-family: 'opendyslexic', sans-serif !important; */
}
@font-face {
   font-family: 'opendyslexic';
   font-style: normal;
   font-weight: 500;
   src: url('../../../custom/fonts/opendyslexic.woff2') format('woff2');
}
```

Step 3: Restart Trilium
