### DISCUSSION TITLE
Customise output when printing

### DISCUSSION THREAD

**Discussion by Elharion6757** [TriliumNext/Trilium#5971] [Ideas] [answered]
Hello,

As my coworker don't use trillium I need to print my notes with a pdf printer when I need to share. 
I would like to know if it is possible to customise the output with a css file or something else.

Could someone help me?

**Comment by eliandoran** [comment]
@Elharion6757 , it is planned but not yet available. 

For now, it's possible to apply a print CSS globally via an #appCss code note with @media for printing. 

Let me know if you need any help.

**Reply by Elharion6757** [reply]
Thank you for your answer.

I am struggling a bit with setting up the #appCss cote note and making it work. Does a guide exists somewhere?

**Reply by eliandoran** [reply, marked as answer]
@Elharion6757 , the relevant documentation is here: https://triliumnext.github.io/Docs/Wiki/themes.html#custom-css

For example, to change the font of the document you could use the following `appCss` note:

```css
@media print {
	body {
        --main-font-family: serif !important;
        --detail-font-family: var(--main-font-family) !important;
    }
}
```
