### DISCUSSION TITLE
Upgrading/migrating a zadam Trilium docker container to a Trilium Next one?

### DISCUSSION THREAD

**Discussion by maphew** [TriliumNext/Trilium#6056] [Ideas] [answered]
What's the process for upgrading or migrating a zadam Trilium docker container to a Trilium Next one?
Are there any stake filled pits and foot guns to be wary of?

**Comment by meichthys** [comment]
Download the new version and run it. That's it. No traps :)
For docker, just update your compose file with the new TriliumNext image from dockerhub.

We get this question enough that we should probably add a section to the readme to clarify this.

**Reply by maphew** [reply]
I'm a docker noob, and in this case am using it via Synology's "Container Manager". Once I figure how to locate and edit the compose file, what do I use for the TNext image name?

![image](https://github.com/user-attachments/assets/2f6e83f2-3e1f-4d50-a141-41e0b55c5583)

**Reply by meichthys** [reply]
https://github.com/orgs/TriliumNext/discussions/369#discussioncomment-10455561

**Comment by eliandoran** [comment, marked as answer]
@maphew , the corresponding image name would be `triliumnext/notes:latest`

You can find an example on the new Docker compose file here: https://github.com/TriliumNext/Notes/blob/develop/docker-compose.yml

**Reply by maphew** [reply]
thanks! 
...it looks like I have homework and research to do in understanding docker, and Synology's use of it. Editing the image name in-place is disabled and I don't want to risk running 2 containers against one database. Well, off to school then!

**Reply by uniquegch** [reply]
I started using zadam/trilium this year and just discovered it is in Maintenance Mode. I have one Server docker based and a couple of clients as Desktop version running on Arch or Debian (12,13).
I did first upgrade the server and for that I only changed the image information in my docker-compose.yaml file. This "inplace" upgrade works and I can also use the Trilium 0.63.7 Desktop version with the server now running TriliumNext Notes. Changes are being synced in both directions.

Here are my steps for the upgrade of the docker-compose.yaml file

1.  ssh into the server
2.  cd /path/to/trilium/container   ### my docker container for trilium is names trilium
3. docker compose stop
4. cp docker-compose.yaml docker-compose.yaml.zadam   ### docker-compose.yml or docker-compose.yaml is the same
5. nano docker-compose.yaml
6. change image from image: _zadam/trilium_:latest to _triliumnext/notes_:latest   ### see the two docker-compose file below
7. cd ..
8. cp -r tilium trilium.bak  ### just have a backup in case the inplace upgrade goes sideways
9. cd trilium
10.  docker compose pull   ### see the output from my machine
11. docker compose up
12. docker compose logs trilium  ### see the output from my maschine and the container_name stays trilium
13. open a webbrowser and enter the URL/IP of the trilium server with port (I am using heimdall as dashboard and click on the trilium link)
14.  login if necessary and click on the flower icon top left. it should show "About Trilium**Next Notes**"

Below the docker-compose.yaml file ### I am running Docker Compose version v2.29.2 and docker-ce  Version:  27.2.1
```
### trilium version from zadam
services:
 trilium:
   image: zadam/trilium:latest
   container_name: trilium
   hostname: trilium
   restart: unless-stopped
   ports:
     - '8201:8080'  ### I am using 8201 in the webbrowser
   environment:
     - PUID=1000
     - PGID=1000
   volumes:
     - ./trilium-data:/home/node/trilium-data  ### I store the data within the container itself thats why ./trilium-data
```
```
### triliumnext notes version
services:
 trilium:
   image: triliumnext/notes:latest
   container_name: trilium
   hostname: trilium
   restart: unless-stopped
   ports:
     - '8201:8080'  ### I am using 8201 in the webbrowser
   environment:
     - PUID=1000
     - PGID=1000
   volumes:
     - ./trilium-data:/home/node/trilium-data  ### I store the data within the container itself thats why ./trilium-data
```

```
### Output from docker compose pull
[+] Pulling 15/15
 ✔ trilium Pulled                                                                                  30.7s 
   ✔ 5de87e84afee Pull complete                                                                     4.1s 
   ✔ ea0c2787dcd2 Pull complete                                                                     4.1s 
   ✔ e971a37af272 Pull complete                                                                     6.7s 
   ✔ 31bc2c2b669f Pull complete                                                                     6.8s 
   ✔ 7862ea6566a7 Pull complete                                                                     6.9s 
   ✔ 9ff11a6775af Pull complete                                                                    13.6s 
   ✔ 940be1f82a18 Pull complete                                                                    13.6s 
   ✔ 59ee54b77aeb Pull complete                                                                    14.1s 
   ✔ 8dd8ed95a18f Pull complete                                                                    14.1s 
   ✔ c92e735f0c1f Pull complete                                                                    14.3s 
   ✔ fa3c8c267e90 Pull complete                                                                    14.4s 
   ✔ d383da088699 Pull complete                                                                    25.0s 
   ✔ b838ac930a4c Pull complete                                                                    25.0s 
   ✔ 4f4fb700ef54 Pull complete                                                                    25.0s   
```

```
###Output from docker compose logs trilium
trilium  | No USER_UID specified, leaving 1000
trilium  | No USER_GID specified, leaving 1000
trilium  | (node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
trilium  | (Use `node --trace-warnings ...` to show where the warning was created)
trilium  | DB size: 18878 KB
trilium  | Becca (note cache) load took 31ms
trilium  | Created option "locale" with default value "en"
trilium  | Created option "firstDayOfWeek" with default value "1"
trilium  | {
trilium  |   "appVersion": "0.90.6-beta",
trilium  |   "dbVersion": 228,
trilium  |   "nodeVersion": "v20.15.1",
trilium  |   "syncVersion": 32,
trilium  |   "buildDate": "2024-09-07T18:36:34Z",
trilium  |   "buildRevision": "7c0d6930fa8f20d269dcfbcbc8f636a25f6bb9a7",
trilium  |   "dataDirectory": "/home/node/trilium-data",
trilium  |   "clipperProtocolVersion": "1.0",
trilium  |   "utcDateTime": "2024-09-19T12:50:44.068Z"
trilium  | }
trilium  | CPU model: AMD Ryzen 7 7735U with Radeon Graphics, logical cores: 16, freq: 1329 Mhz
trilium  | Trusted reverse proxy: false
trilium  | App HTTP server starting up at port 8080
trilium  | Listening on port 8080
trilium  | 200 GET /api/health-check with 15 bytes took 6ms
trilium  | Table counts: notes: 769, revisions: 1380, attachments: 475, branches: 786, attributes: 856, etapi_tokens: 0, blobs: 1911
trilium  | All consistency checks passed with no errors detected (took 42ms)
```
