### DISCUSSION TITLE
Trilium fails to access existing volume path in WSL2 Docker (ENOENT: no such file or directory)

### DISCUSSION THREAD

**Discussion by dominic248** [TriliumNext/Trilium#6136] [Q&A]
### Description

Hello Trilium Team,

I'm facing a directory access issue when trying to run Trilium via Docker in a WSL2 environment on Windows using Docker Desktop.

**Issue:**
Trilium throws the following error during startup: 
`Error: ENOENT: no such file or directory, mkdir '/home/dms24/trilium-data'`
![Image](https://github.com/user-attachments/assets/729f462c-246d-4a4a-ba5a-579b25e03cda)
![Image](https://github.com/user-attachments/assets/536a9679-cc0e-424b-9c90-f8e5c4413d10)

**NOTE:**
- The specified `TRILIUM_DATA_DIR` path **does exist** in WSL (`/home/dms24/trilium-data`).
- Other self-hosted apps (e.g., Linkding, KaraKeep) using the same volume path **works without any issues**.

**Environment:**
- Windows 11 + WSL2 (Ubuntu 24.04.2 LTS)
- Docker Desktop with WSL integration enabled
- Trilium image: `triliumnext/notes:latest`
- `docker-compose.yml` file:
  ```
  services:
    trilium:
      image: triliumnext/notes:latest 
      restart: unless-stopped
      environment:
        - TRILIUM_DATA_DIR=/home/dms24/trilium-data
      ports:
        - '8001:8080'
      volumes:
        # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
        - ${TRILIUM_DATA_DIR:-~/trilium-data}:/home/node/trilium-data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
```

### TriliumNext Version

0.95.0

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11 Pro Version-24H2 Build-26100.4349

### Error logs

```No USER_UID specified, leaving 1000

No USER_GID specified, leaving 1000

node:fs:1364

  const result = binding.mkdir(

                         ^


Error: ENOENT: no such file or directory, mkdir '/home/dms24/trilium-data'

    at Object.mkdirSync (node:fs:1364:26)

    at Upe (/usr/src/app/main.cjs:1:43307)

    at _bn (/usr/src/app/main.cjs:1:42202)

    at /usr/src/app/main.cjs:1:43473

    at /usr/src/app/main.cjs:1:231

    at /usr/src/app/main.cjs:6:4990

    at /usr/src/app/main.cjs:1:231

    at /usr/src/app/main.cjs:805:2768

    at /usr/src/app/main.cjs:1:231

    at /usr/src/app/main.cjs:805:3417 {

  errno: -2,

  code: 'ENOENT',

  syscall: 'mkdir',

  path: '/home/dms24/trilium-data'

}


Node.js v22.16.0

No USER_UID specified, leaving 1000

No USER_GID specified, leaving 1000

node:fs:1364

  const result = binding.mkdir(```

**Comment by perfectra1n** [comment]
Yes, but the path `/home/dms24/trilium-data` doesn't exist within the _container_, which is why the container is saying that it can't find the directory.

When you added:
```
    environment:
      - TRILIUM_DATA_DIR=/home/dms24/trilium-data
```

You modified the container's environment to have `TRILIUM_DATA_DIR` set to `/home/dms24/trilium-data`, which is why the container is saying it can't find it. It's trying to read from that exact directory within the container, as you modified the environment variable of the container. Don't set that.

This line:
```
${TRILIUM_DATA_DIR:-~/trilium-data}:/home/node/trilium-data
```

Is reading from the process that *starts* the Docker Compose stack, so you'd need to have `TRILIUM_DATA_DIR` set at that time when running it, which is what I assume you're trying to do. See the attached screenshot.

![Image](https://github.com/user-attachments/assets/d74a18af-1757-4594-86bf-87bdf64096b9)

The above image, and me setting the environment variable and having it work as I assume you expect, is with this `docker-compose.yml`:
```yml
services:
  trilium:
    image: triliumnext/notes:latest
    restart: unless-stopped
    ports:
      - '8001:8080'
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      - ${TRILIUM_DATA_DIR:-~/trilium-data}:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

**Comment by perfectra1n** [comment]
Or instead of relying on environment variables (which is where I believe you're confused), swap out:
```yml
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      - ${TRILIUM_DATA_DIR:-~/trilium-data}:/home/node/trilium-data
```

for
```yml
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      - /home/dms24/trilium-data:/home/node/trilium-data
```

For a total docker compose file of:
```yml
services:
  trilium:
    image: triliumnext/notes:latest
    restart: unless-stopped
    ports:
      - '8001:8080'
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      - /home/dms24/trilium-data:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```
