### DISCUSSION TITLE
(Bug report) Unable to store attachments larger than 250 MB

### DISCUSSION THREAD

**Discussion by miltuss** [TriliumNext/Trilium#7330] [Q&A] [answered]
### Trilium Version

0.63.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Debian server

### Description

Hello, I use trilium (docker) only with the web client on my server, but I cannot disable the file size limit set to 250 MB.  However, I added the following environment variable in the docker-compose file
 `- TRILIUM_NO_UPLOAD_LIMIT=1` 
 I also added it to the trilium config.ini file, but the 250MB limit has still not been deactivated!

 How to disable this restriction?

**Comment by Nriver** [comment]
It works on my machine. I guess you did not set it right.

Just tested a big file, works fine.
![snipaste20240330_184721](https://github.com/zadam/trilium/assets/6752679/5eeb5747-6222-47ac-95d2-0d21e619b005)

Do you have something like Nginx in the front? There is also a upload limit in it.

**Comment by miltuss** [comment]
> Do you have something like Nginx in the front? There is also a upload limit in it.

I don't use reverse proxy.  Here is the docker compose file that I use :

```
version: '2.1'
services:
  trilium:
    image: zadam/trilium
    container_name: trilium
    networks:
        work:
            ipv4_address: 10.100.0.100
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - TRILIUM_NO_UPLOAD_LIMIT=1
    ports:
      - 7000:8080
    volumes:
      - /data/trilium:/home/node/trilium-data
    restart: always

networks:
    work:
        external: true
```

Is there something I did wrong?
