### DISCUSSION TITLE
(Feature request)

### DISCUSSION THREAD

**Discussion by chncho** [TriliumNext/Trilium#8627] [Q&A]
### Describe feature

version 0.62.5

1. I have added the following style so that when the phone is horizontally displayed, the height is not enough and the left splitter bar can scroll up and down.
2. When I finished adding, the left splitter bar could indeed scroll up and down, but when I clicked on it, there was no response.
3. When I use it on the desktop, I adjust the window schedule very little, and the same goes for it. When I place the mouse on the button in the launcher, the shape of the mouse constantly changes between the pointer and the hand shape.
4. May I ask what the reason is and is there any way to avoid it

```css

button.button-widget.bx.component.launcher-button {
    flex-shrink: 0;
}
div#launcher-container {
    overflow: scroll;
}

```
