### ISSUE TITLE
(Feature request) Tabless mode

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#3776]
### Describe feature

I often find myself having multiple tabs open when I only intend to be working on one note at a time. When i want to work on multiple notes, i generally just open a new split so i can work on the notes at the same time.

It would be nice if there was a way to disable tabs so only one note could be open at a time.

Although less clean, it may be easier to just limit the workspace to a single tab.

**Comment by mikkel1156** [comment]
Just a thought, but have you looked into a simple theme? However it might work unexpectedly if you press some shortcut to create new tabs I imagine.

**Comment by Mangiola** [comment]
I use this CSS workaround to hide the tab bar unless there's more than one tab. Less clutter by default, but you retain the ability to open multiple tabs by middle-clicking a link.

```css
/* Hide tabs if there is only one */
#rest-pane > div:first-child:has(.note-tab:first-child:nth-last-child(2)) {
    display: none !important;
}
/* Remove main panel rounded corners when tabs are hidden */
.vertical-layout:has(.note-tab:first-child:nth-last-child(2)) #center-pane {
    border-radius: 0px !important;
}
```

Paste this in a CSS note with the  `#appCss` attribute. 

Note that this likely only works in the web app; I haven't tested how it interacts with a native title bar and window controls.
