### ISSUE TITLE
(Feature request) Different application logo

### ISSUE THREAD

**Issue by funkinlab** [TriliumNext/Trilium#4103]
### Describe feature

Logo too ugly！！

**Comment by XXXJetfireXXX** [comment]
If it bothers you within the program itself (menu button), you can replace the image with anything you want.

Paste the following code in your custom theme:
```css
body .global-menu-button{
    /*tweak the url according to where the image note is*/
    background-image: url("../../images/<note id>/<image file name>");
    /*the following rules are used to tweak the image's position*/
    position: relative;
    background-size: 30px;
    background-position: center;
}

body .global-menu-button:hover{
    /*here you can define what happens when you hover over the button*/
}
```

Image path can be found like so:
![image](https://github.com/zadam/trilium/assets/43646178/c43e3cf7-c8c0-45c2-9983-8e143c0c5a1f)

Example:
![image](https://github.com/zadam/trilium/assets/43646178/f4d83661-29c0-4f48-b773-e0264269306f)
