### ISSUE TITLE
(Feature request) Some sort of user supplied CSS classes for paragraphs

### ISSUE THREAD

**Issue by origintopleft** [TriliumNext/Trilium#4309]
### Describe feature

A common pattern I want to put in my notes is a box like this: 
![image](https://github.com/zadam/trilium/assets/4407155/c67c3a1b-d8fe-437a-ada3-7431e3fac9dd)

Not necessarily a warning box specificially, but a highlighted, separate colored "box" with some information in it. I'm proposing Trilium provides some way to provide custom class names for arbitrary paragraphs within a note, so that someone like me can design her own box classes and use them as appropriate.

(The main reason I'm suggesting custom classes instead of "give me warning boxes" is because I don't necessarily want to impose anything on other users, who may not want or need this particular feature, but want some other pattern that could be implemented with CSS classes)

### Additional Information

I'm not very good at electron apps, but if I can figure out how to design a theme for Trilium, I don't see what's stopping me from having a look through and seeing if I can't kludge an implementation myself in my off hours.

**Comment by rauenzi** [comment]
In the meantime, you could override the styling for a specific background color in the notes by doing something like this:

```css
p > span[style*="hsl(30, 75%, 60%)"] {
    display: flex;
    padding: 10px;
    border-left: 4px solid #CF4D03;
    background: #FEE3D3 !important; /* important to override default background */
    color: #CF4D03;
    font-weight: 700;
    align-items: center;
    gap: 10px;
}

p > span[style*="hsl(30, 75%, 60%)"]::before {
    content: "";
    display: flex;
    color: red;
    currentColor: red;
    width: 32px;
    height: 32px;
    background: url(data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M12.884 2.532c-.346-.654-1.422-.654-1.768 0l-9 17A.999.999 0 0 0 3 21h18a.998.998 0 0 0 .883-1.467L12.884 2.532zM13 18h-2v-2h2v2zm-2-4V9h2l.001 5H11z"></path></svg>) no-repeat;
}
```

then you get something like this:


https://github.com/zadam/trilium/assets/6865942/2660a699-20ba-43f4-98d9-744c2fc523b2
