### ISSUE TITLE
(Bug report) v0.90.4 docker does not read USER_UID and USER_GID from environment

### ISSUE THREAD

**Issue by yu-jingrui** [TriliumNext/trilium#5131]
### TriliumNext Version

0.90.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

windows 11

### Description

Docker server is deployed on synology DS920+ with container manager. After updating to 0.90.4 from 0.94.3, the docker instance shuts down with error code -13. It keeps setting uid and gid to 1000 although they are specified in environment. Here is the compose file:
```
version: "3"
services:
  trilium:
    image: triliumnext/notes:v0.90.4
    container_name: triliumnext
    restart: unless-stopped
    hostname: triliumnext
    volumes:
      - ./trilium-data:/home/node/trilium-data
    environment:
      USER_UID: xxxx
      USER_GID: xxxxx
    ports:
      - xxxxx:8080
```

### Error logs

2024/8/11 16:09	stderr	Node.js v20.15.1	
2024/8/11 16:09	stderr
2024/8/11 16:09	stderr	}
2024/8/11 16:09	stderr	  path: '/home/node/trilium-data/log'
2024/8/11 16:09	stderr	"  syscall: 'mkdir',"
2024/8/11 16:09	stderr	"  code: 'EACCES',"
2024/8/11 16:09	stderr	"  errno: -13,"
2024/8/11 16:09	stderr	    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
2024/8/11 16:09	stderr	    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
2024/8/11 16:09	stderr	    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
2024/8/11 16:09	stderr	    at file:///usr/src/app/src/services/log.js:6:8
2024/8/11 16:09	stderr	    at Object.mkdirSync (node:fs:1372:26)
2024/8/11 16:09	stderr	"Error: EACCES: permission denied, mkdir '/home/node/trilium-data/log'"
2024/8/11 16:09	stderr	
2024/8/11 16:09	stderr	                         ^
2024/8/11 16:09	stderr	  const result = binding.mkdir(
2024/8/11 16:09	stderr	node:fs:1372
2024/8/11 16:09	stderr	(Use `node --trace-warnings ...` to show where the warning was created)
2024/8/11 16:09	stderr	(node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
2024/8/11 16:09	stdout	"No USER_GID specified, leaving 1000"
2024/8/11 16:09	stdout	"No USER_UID specified, leaving 1000"
2024/8/11 16:09	stderr	./start-docker.sh: 4: [[: not found
2024/8/11 16:09	stderr	./start-docker.sh: 3: [[: not found
2024/8/11 16:09	stderr	Node.js v20.15.1
2024/8/11 16:09	stderr	
2024/8/11 16:09	stderr	}
2024/8/11 16:09	stderr	  path: '/home/node/trilium-data/log'
2024/8/11 16:09	stderr	"  syscall: 'mkdir',"
2024/8/11 16:09	stderr	"  code: 'EACCES',"
2024/8/11 16:09	stderr	"  errno: -13,"
2024/8/11 16:09	stderr	    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
2024/8/11 16:09	stderr	    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
2024/8/11 16:09	stderr	    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
2024/8/11 16:09	stderr	    at file:///usr/src/app/src/services/log.js:6:8
2024/8/11 16:09	stderr	    at Object.mkdirSync (node:fs:1372:26)
2024/8/11 16:09	stderr	"Error: EACCES: permission denied, mkdir '/home/node/trilium-data/log'"
2024/8/11 16:09	stderr	
2024/8/11 16:09	stderr	                         ^
2024/8/11 16:09	stderr	  const result = binding.mkdir(
2024/8/11 16:09	stderr	node:fs:1372
2024/8/11 16:09	stderr	(Use `node --trace-warnings ...` to show where the warning was created)
2024/8/11 16:09	stderr	(node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
2024/8/11 16:09	stdout	"No USER_GID specified, leaving 1000"
2024/8/11 16:09	stdout	"No USER_UID specified, leaving 1000"
2024/8/11 16:09	stderr	./start-docker.sh: 4: [[: not found
2024/8/11 16:09	stderr	./start-docker.sh: 3: [[: not found

**Comment by LancelotOho** [comment]
```yaml
compose:
services:
  trilium:
    image: docker.1ms.run/triliumnext/trilium:latest
    container_name: trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - TZ=Asia/Shanghai
    networks: 
      - trilium
    ports:
      - '8100:8080'
    volumes:
      - ./trilium-data:/home/node/trilium-data
networks:
  trilium:
    driver: bridge
    name: trilium    
```

logs:
```
path: '/home/node/trilium-data/tmp'
syscall: 'mkdir',
code: 'EACCES',
errno: -13,
at /usr/src/app/main.cjs:1098:3486 {
at /usr/src/app/main.cjs:1:230
at /usr/src/app/main.cjs:1098:2772
at /usr/src/app/main.cjs:1:230
at /usr/src/app/main.cjs:8:211502
at /usr/src/app/main.cjs:1:230
at /usr/src/app/main.cjs:1:44668
at Ern (/usr/src/app/main.cjs:1:44160)
at HJ (/usr/src/app/main.cjs:1:44493)
at Object.mkdirSync (node:fs:1349:26)
Error: EACCES: permission denied, mkdir '/home/node/trilium-data/tmp'
const result = binding.mkdir(
node:fs:1349
No USER_GID specified, leaving 1000
No USER_UID specified, leaving 1000
Node.js v24.12.0
```

so what can i do now~~
