### ISSUE TITLE
(Bug report) Check failed: module->status() == kLinked || module->status() == kEvaluated.

### ISSUE THREAD

**Issue by phamleduy04** [TriliumNext/Trilium#5172]
### TriliumNext Version

0.90.4

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Ubuntu 24.04 LTS

### Description

I tried with `latest` tag and `develop` tag but always showing this error.

docker-compose file

```yml
# Running `docker-compose up` will create/use the "trilium-data" directory in the user home
# Run `TRILIUM_DATA_DIR=/path/of/your/choice docker-compose up` to set a different directory
# To run in the background, use `docker-compose up -d`
services:
  trilium:
    # Optionally, replace `latest` with a version tag like `v0.90.3`
    # Using `latest` may cause unintended updates to the container
    image: triliumnext/notes:sha-d7ab990
    # Restart the container unless it was stopped by the user
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    # ports:
      # By default, Trilium will be available at http://localhost:8080
      # It will also be accessible at http://<host-ip>:8080
      # You might want to limit this with something like Docker Networks, reverse proxies, or firewall rules, such as UFW
      # - '8080:8080'
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      # This can also be changed with by replacing the line below with `- /path/of/your/choice:/home/node/trilium-data
      - nas:/home/node/trilium-data
    networks:
      - proxy

volumes:
  nas:
    driver: local
    driver_opts:
      type: cifs
      o: "username=,password=,vers=3.0,file_mode=0777,dir_mode=0777"
      device: "//IP_ADDRESS/notes"

networks:
  proxy:
    external: true
```

### Error logs

```
$ sudo docker compose logs -f
trilium-1  | No USER_UID specified, leaving 1000
trilium-1  | No USER_GID specified, leaving 1000
trilium-1  | (node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
trilium-1  | (Use `node --trace-warnings ...` to show where the warning was created)
trilium-1  |
trilium-1  |
trilium-1  | #
trilium-1  | # Fatal error in , line 0
trilium-1  | # Check failed: module->status() == kLinked || module->status() == kEvaluated.
trilium-1  | #
trilium-1  | #
trilium-1  | #
trilium-1  | #FailureMessage Object: 0x7ffffa582060
trilium-1  | ----- Native stack trace -----
trilium-1  |
trilium-1  |  1: 0xd36951  [node]
trilium-1  |  2: 0x216c041 V8_Fatal(char const*, ...) [node]
trilium-1  |  3: 0x13fe852 v8::internal::SourceTextModule::Evaluate(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SourceTextModule>) [node]
trilium-1  |  4: 0xf0fafa v8::Module::Evaluate(v8::Local<v8::Context>) [node]
trilium-1  |  5: 0xc6811b node::loader::ModuleWrap::Evaluate(v8::FunctionCallbackInfo<v8::Value> const&) [node]
trilium-1  |  6: 0xf562bf v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [node]
trilium-1  |  7: 0xf56b2d  [node]
trilium-1  |  8: 0xf56ff5 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
trilium-1  |  9: 0x1961df6  [node]
trilium-1  | Trace/breakpoint trap (core dumped)
trilium-1 exited with code 0
