### ISSUE TITLE
(Feature request) Disable text selection in mermaid diagrams?

### ISSUE THREAD

**Issue by dousha** [TriliumNext/trilium#5201]
### Describe feature

Some mermaid diagrams can be dragged around to navigate. However, dragging would also highlight text in the diagram. If the start point of dragging happened to be a part of the highlighted text, dragging would instead perform other actions (such as "search" in Edge).

It can be implemented using custom CSS:

```css
.mermaid-render {
    user-select: none;
    -webkit-user-select: none;
    -webkit-user-drag: auto;
}
```

I wonder if it would be better if it is added as a configurable option?
