### ISSUE TITLE
Llama3.1 doesn't work

### ISSUE THREAD

**Issue by mobamoba** [TriliumNext/Trilium#5789]
### Description

You can select llama3.1 from the dropdown but Trilium searches for llama3 and doesn't find it - something in the system isn't adding the .1.
Here's the error message:
Ollama embedding error: model "llama3" not found, try pulling it first

When I pulled llama3 it worked fine, but I wanted to use llama3.1 and that's the error I got after select 3.1.

### TriliumNext Version

.94.1

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Firefox

**Comment by PlanarFox** [comment]
I've also encountered this error on version 0.94.1, even with a fresh new docker container created by this docker compose file:
```yml
services:
  trilium:
    image: triliumnext/notes:latest
    restart: unless-stopped
    ports:
      - '58080:8080'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

The logs are filled with things like:
```log
ERROR: Ollama embedding error: model "llama3" not found, try pulling it first
ERROR: Error generating embedding with provider ollama for note BS8Id7fTM7h9: Ollama embedding error: model "llama3" not found, try pulling it first
ERROR: Ollama embedding error: model "llama3" not found, try pulling it first
ERROR: Error generating embedding with provider ollama for note szkrCF7EZsou: Ollama embedding error: model "llama3" not found, try pulling it first
```

The host machine of docker is running Manjaro 25.0.3. The error happens with both firefox and chrome.
I'm serving Ollama on another local machine without docker and I can use it with Cherry Studio so it's no likely to be Ollama's problem. I've tried several embedding models including Qwen3-Embedding-4B-GGUF, bge-large and mxbai-embed-large, all with the same error in log.
